import{i as c,S as d}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function u({views:o,downloads:t,likes:s,comments:a,webformatURL:e,largeImageURL:r,tags:i}){return`<li class="card">
      <a class="card-image-wrapper" href="${r}">
        <img class="card-image" src="${e}" alt="${i}" data-full="${r}">
      </a>
      <ul class="card-content">
        <li class="card-content-item">Likes <span data-likes="">${s}</span></li>
        <li class="card-content-item">Comments <span data-comments="">${a}</span></li>
        <li class="card-content-item">Views <span data-views="">${o}</span></li>
        <li class="card-content-item">Downloads <span data-downloads="">${t}</span></li>
      </ul>
    </li>`}function m(o){return o.map(t=>u(t)).join("")}const f="https://pixabay.com",p="/api/";function h(o){o=o.toLowerCase().split(" ").join("+").toString();const t=new URLSearchParams({key:"44447717-1f020d7968b38ed176a967b4c",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"}),s=`${f}${p}?${t}`;return fetch(s).then(a=>a.json()).catch(a=>console.log(a))}const n={form:document.querySelector(".entry-form"),input:document.querySelector(".entry-form-input"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")},g={titleColor:"#FFFFFF",messageColor:"#FFFFFF",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",message:"Sorry, there are no images matching<br>your search query.Please try again!",position:"topRight",iconUrl:"../img/sad.svg"},y={captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.8};let l;function L(){n.loader.classList.remove("visually-hidden")}function F(){n.loader.classList.add("visually-hidden")}function b(o){n.gallery.innerHTML="",L(),h(o).then(t=>{if(t.hits.length===0){c.show(g);return}const s=m(t.hits);n.gallery.insertAdjacentHTML("afterbegin",s),l=new d(".gallery a",y),l.refresh(),l.on("show.simplelightbox")}).catch(t=>{c.error({message:"Sorry, there was an error fetching images. Please try again later!",maxWidth:"322px",iconUrl:closeImageURL,backgroundColor:"#EF4040",messageColor:"#fff",titleColor:"#fff",theme:"dark"})}).finally(()=>F())}n.form.addEventListener("submit",o=>{o.preventDefault();const t=n.input.value.trim();b(t),n.form.reset()});
//# sourceMappingURL=commonHelpers.js.map
